# Debug Workflow: Fix Validation
name: debug-validate-fix
description: "Verify proposed fix addresses root cause without side effects. Includes regression risk assessment."
author: "BMad"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/bmad/bmm/workflows/debug/validate-fix"
instructions: "{installed_path}/instructions.md"
template: false

tags:
  - debug
  - validation
  - quality
  - risk-assessment

execution_hints:
  interactive: true
  autonomous: false
  iterative: false
