# Debug Workflow: Fagan Inspection
name: debug-inspect
description: 'Comprehensive Fagan inspection for systematic bug analysis and resolution. Achieves 60-90% defect detection rates through formal 6-phase methodology.'
author: 'BMad'

config_source: '{project-root}/bmad/debug/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

installed_path: '{project-root}/bmad/debug/workflows/inspect'
instructions: '{installed_path}/instructions.md'
template: '{installed_path}/template.yaml'

# Output configuration
default_output_file: '{output_folder}/debug/debug-report-{{date}}.md'

# Knowledge fragments to load
knowledge_fragments:
  - '{project-root}/bmad/debug/knowledge/debug-inspection-checklist.md'
  - '{project-root}/bmad/debug/knowledge/common-defects.md'
  - '{project-root}/bmad/debug/knowledge/debug-patterns.md'

tags:
  - debug
  - inspection
  - fagan
  - quality

execution_hints:
  interactive: true
  autonomous: false
  iterative: true
