# Debug Workflow: Quick Debug
name: debug-quick
description: 'Rapid triage and initial analysis for simple issues. Provides immediate assessment and suggested next steps.'
author: 'BMad'

config_source: '{project-root}/bmad/debug/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

installed_path: '{project-root}/bmad/debug/workflows/quick-debug'
instructions: '{installed_path}/instructions.md'
template: false

tags:
  - debug
  - triage
  - quick-analysis

execution_hints:
  interactive: true
  autonomous: false
  iterative: false
