/**
 * Global Setup for Unified Testing Framework
 *
 * For Manual LLM-Evaluated tests, it ensures Copilot Proxy is running.
 */

import {
  startCopilotProxy,
  stopCopilotProxy,
} from '../../support/copilot-helper.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';

/**
 * Global setup - Clean old test result fragments and contexts for this test type
 *
 * Each test type (unit, integration, e2e) has its own subdirectory in .results
 * so they can run independently without interfering with each other.
 */
export async function setup() {
  // Set git auto-update to false for all tests to prevent git lock conflicts
  process.env.BMAD_GIT_AUTO_UPDATE = 'false';

  const testType = process.env.TEST_TYPE || 'default';
  const resultsDir = path.join(
    process.cwd(),
    'test-results/.results',
    testType,
  );

  // Detect if we're running manual/llm-evaluated tests from command line args
  // Only auto-start Copilot Proxy if explicitly requested
  const isRunningEvaluatedTests =
    process.env.RUN_LLM_EVALUATION === 'true' ||
    process.env.AUTO_START_COPILOT === 'true';

  try {
    // Remove old fragments and contexts for this test type only
    await fs.rm(resultsDir, { recursive: true, force: true });
    console.log(`🧹 Cleaned old ${testType} test results and contexts`);
  } catch {
    // Directories don't exist, that's fine
  }

  // For Manual LLM-Evaluated tests, ensure Copilot Proxy is running
  // Only if explicitly requested via environment variable
  if (isRunningEvaluatedTests) {
    console.log('\n🔍 Checking Copilot Proxy for LLM evaluation tests...');
    console.log('   Set AUTO_START_COPILOT=true to auto-start proxy\n');

    try {
      // This will throw if authentication fails or server can't start
      await startCopilotProxy();
    } catch (err) {
      const error = err as Error;
      // Warn but don't fail - manual tests should handle unavailability
      console.warn('\n⚠️  WARNING: Copilot Proxy startup failed');
      console.warn('   Error:', error.message);
      console.warn('\n   Manual LLM evaluation tests may be skipped.');
      console.warn('   To enable: npx copilot-proxy --auth\n');
    }
  }
}

/**
 * Global teardown - Cleanup after all tests complete
 */
export async function teardown() {
  // Stop Copilot Proxy if it was started
  try {
    await stopCopilotProxy();
  } catch (err) {
    const error = err as Error;
    console.warn('⚠️  Error stopping Copilot Proxy:', error.message);
  }

  console.log(
    '\n✅ Test run complete. Reports generated by Vitest reporters.\n',
  );
}
