blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/mkellerman/bmad-mcp-server/discussions
    about: Please start a discussion for questions or general feedback.
