# Debug Workflow: Wolf Fence (Binary Search)
name: debug-wolf-fence
description: "Execute binary search debugging to isolate bug location efficiently. Highly effective for large codebases."
author: "BMad"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/bmad/bmm/workflows/debug/wolf-fence"
instructions: "{installed_path}/instructions.md"
template: false

tags:
  - debug
  - binary-search
  - isolation
  - advanced

execution_hints:
  interactive: true
  autonomous: false
  iterative: true
