# Debug Workflow: Pattern Analysis
name: debug-pattern-analysis
description: "Analyze recent commits and code changes for defect patterns and systemic issues."
author: "BMad"

config_source: "{project-root}/bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

installed_path: "{project-root}/bmad/bmm/workflows/debug/pattern-analysis"
instructions: "{installed_path}/instructions.md"
template: false

knowledge_fragments:
  - "{project-root}/bmad/bmm/debug/knowledge/debug-patterns.md"
  - "{project-root}/bmad/bmm/debug/knowledge/common-defects.md"

tags:
  - debug
  - pattern-detection
  - analysis
  - prevention

execution_hints:
  interactive: false
  autonomous: true
  iterative: true
