# Build Module Workflow Configuration
name: build-module
description: "Interactive workflow to build complete BMAD modules with agents, workflows, tasks, and installation infrastructure"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/bmad/bmb/config.yaml"
output_folder: "{config_source}:output_folder"
src_impact: "{config_source}:src_impact"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"
date: system-generated

# Reference guides for module building
module_structure_guide: "{installed_path}/module-structure.md"
installer_templates: "{installed_path}/installer-templates/"
example_modules: "{installed_path}/example-modules.md"

# Use existing build workflows
agent_builder: "{project-root}/bmad/bmb/workflows/build-agent/workflow.yaml"
workflow_builder: "{project-root}/bmad/bmb/workflows/build-workflow/workflow.yaml"

# Optional docs that help understand module patterns
recommended_inputs:
  - module_brief: "{output_folder}/module-brief-*.md"
  - brainstorming_results: "{output_folder}/brainstorming-*.md"
  - bmm_module: "{project-root}/bmad/bmm/"
  - cis_module: "{project-root}/bmad/cis/"
  - existing_agents: "{project-root}/bmad/*/agents/"
  - existing_workflows: "{project-root}/bmad/*/workflows/"

# Module path and component files
installed_path: "{project-root}/bmad/bmb/workflows/build-module"
template: false # This is an interactive scaffolding workflow
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Output configuration - creates entire module structure
# If src_impact=true: Save to src/modules/{{module_code}}
# If src_impact=false: Save to output_folder/{{module_code}}
default_output_folder: "{output_folder}/{{module_code}}"
src_output_folder: "{project-root}/src/modules/{{module_code}}"
installer_output_folder: "{output_folder}/{{module_code}}"
src_installer_output_folder: "{project-root}/src/modules/{{module_code}}"

# No special tools required for module building
required_tools: []
