# Debug Workflow: Pattern Analysis
name: debug-pattern-analysis
description: 'Analyze recent commits and code changes for defect patterns and systemic issues.'
author: 'BMad'

config_source: '{project-root}/bmad/debug/config.yaml'
output_folder: '{config_source}:output_folder'
user_name: '{config_source}:user_name'
communication_language: '{config_source}:communication_language'
date: system-generated

installed_path: '{project-root}/bmad/debug/workflows/pattern-analysis'
instructions: '{installed_path}/instructions.md'
template: false

knowledge_fragments:
  - '{project-root}/bmad/debug/knowledge/debug-patterns.md'
  - '{project-root}/bmad/debug/knowledge/common-defects.md'

tags:
  - debug
  - pattern-detection
  - analysis
  - prevention

execution_hints:
  interactive: false
  autonomous: true
  iterative: true
